name: "Stoney kernel"
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 5120
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - name: Check out
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt update; sudo apt install -y git build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison binutils linux-firmware
      - name: Build kernel
        run: bash build.sh none
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stoney-kernel
          path: |
            build/kernel.tar.gz
